# .air.toml

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd"
bin = "tmp/main.exe"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "test"]
include_ext = ["go", "tpl", "tmpl", "html"]
include = ["**/*.go"]
exclude_regex = ["_test.go"]

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[logger]
time = true
