# .air.toml

root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
bin = "./tmp/main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
include_dir = ["cmd", "models", "routes", "controllers", "middleware", "config", "repository", "utils"]
exclude_dir = ["assets", "tmp", "vendor", "test"]
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = false
follow_symlink = true
log = "air.log"
delay = 100
stop_on_error = true
send_interrupt = true
kill_delay = "0s"
poll = true
poll_interval = 300

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[logger]
time = true
