services:
  app:
    build:
      context: .
      target: dev
    environment:
        - ENV=dev
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - .ENV
    networks:
      - app-network

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 