version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .ENV
    networks:
      - app-network

  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 